# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glgl_app', '0003_auto_20160726_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tempCate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='cover',
            field=models.ImageField(default='default/default.jpg', upload_to='covers'),
        ),
    ]
