# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glgl_app', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='tempCate',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='video',
            name='category_set',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
