# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glgl_app', '0006_auto_20160727_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextraprofile',
            old_name='UDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='userextraprofile',
            old_name='UNickName',
            new_name='nickName',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='Category',
            new_name='category',
        ),
    ]
