# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glgl_app', '0008_auto_20160727_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='categoryName',
            field=models.CharField(default='', max_length=20),
        ),
    ]
