# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('glgl_app', '0009_video_categoryname'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
