# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glgl_app', '0015_auto_20160728_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextraprofile',
            name='videoUploaded',
            field=models.ManyToManyField(related_name='videoUploaded', to='glgl_app.Video'),
        ),
    ]
