# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glgl_app', '0017_userextraprofile_headimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='like_list',
            field=models.ManyToManyField(to='glgl_app.UserExtraProfile'),
        ),
    ]
