# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glgl_app', '0018_video_like_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextraprofile',
            name='headimage',
            field=models.ImageField(default='default/defaulthead.jpg', upload_to='headimages'),
        ),
    ]
